language: python

sudo : false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

branches:
  only:
    - master
    
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
  
install:
  - pip install -q Django==$DJANGO_VERSION
script: python mytestmodule.py

notifications:
  email:
    recipients:
      - matis.ghiotto@gmail.com   
    on_success: change
    on_failure: always
