language: python

sudo : false
python:
  - "3.6.4"
packages:
  - python-scipy
global:
  -act = logistic
  
matrix:
  - hid = 5
  - hid = 10
  - hid = 15
  - hid = 20
  - hid = 25
  - hid = 30
  
  
branches:
  only:
    - master
    
install:
  - pip install numpy scipy scikit-learn

script: python3 TP5.py $hid $act

